name: Android CI

on:
  push:
      branches:
        - 'master'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
      KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
      KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

    steps:
      
      - uses: actions/checkout@v3

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle    
        uses: gradle/gradle-build-action@v2  
          
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

#      - name: Cache Ruby - Bundler
#        uses: actions/cache@v2
#        with:
#          path: vendor/bundle
#          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-gems-
            
      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

#      - name: Install bundle
#        run: |
#          bundle config path vendor/bundle
#          bundle install --jobs 4 --retry 3

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.ANDROID_KEYSTORE_FILE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/prod_keystore.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build prod
        run: ./gradlew app:bundleRelease


#      - name: Distribute app to Production 🚀
#        run: bundle exec fastlane deploy
